// Banner content lives here so it works both from file:// and on GitHub Pages.
// inspiration: attributed excerpts with provenance. humor: selected reader examples
// plus original tracker lines. Keep uncertain authors as Unknown, never guess a name.
const TRACKER_CONTENT = {
  inspiration: [
    { text: "Stay hungry. Stay foolish.", credit: "Steve Jobs · Speech: Stanford commencement, 2005", url: "https://news.stanford.edu/stories/2005/06/steve-jobs-2005-graduates-stay-hungry-stay-foolish" },
    { text: "No! Try not. Do. Or do not. There is no try.", credit: "Yoda · Movie: The Empire Strikes Back", url: "https://www.starwars.com/news/empire-at-40-teaching-with-star-wars-the-wisdom-of-do-or-do-not" },
    { text: "One child, one teacher, one pen and one book can change the world.", credit: "Malala Yousafzai · Speech: United Nations, 2013", url: "https://malala.org/news-and-voices/malala-un-speech" },
    { text: "It’s your place in the world; it’s your life. Go on and do all you can with it…", credit: "Mae Jemison · Person", url: "https://ntrs.nasa.gov/api/citations/20190032275/downloads/20190032275.pdf?attachment=true" },
    { text: "What I cannot create, I do not understand.", credit: "Richard Feynman · Person", url: "https://magazine.caltech.edu/post/biology-through-the-eyes-of-a-physicist" },
    // Monkeytype trial picks from:
    // https://github.com/monkeytypegame/monkeytype/blob/master/frontend/static/quotes/english.json
    // IDs preserve provenance for review; these are not claims of speaker-level verification.
    { text: "You must take life the way it comes at you and make the best of it.", credit: "Book: Life of Pi", monkeytypeId: 6 },
    { text: "There are darknesses in life, and there are lights; you are one of the lights.", credit: "Book: Dracula", monkeytypeId: 14, url: "https://www.gutenberg.org/files/345/345-h/345-h" },
    { text: "If you only do what you can do, you will never be more than who you are now.", credit: "Movie: Kung Fu Panda", monkeytypeId: 16 },
    { text: "Courage is resistance to fear, mastery of fear—not absence of fear.", credit: "Mark Twain · Book: Pudd’nhead Wilson", monkeytypeId: 36, url: "https://quoteinvestigator.com/2019/11/26/courage-fear/" },
    { text: "If you want a happy ending, that depends, of course, on where you stop your story.", credit: "Show: White Collar", monkeytypeId: 844 },
    { text: "When do I know I'm Spider-Man? You won't. That's all it is Miles. A leap of faith.", credit: "Movie: Spider-Man: Into the Spider-Verse", monkeytypeId: 5737 },
    { text: "There is nothing wrong with letting the people who love you help you.", credit: "Show: Avatar: The Last Airbender", monkeytypeId: 5396 },
    { text: "Your story may not have such a happy beginning, but that doesn't make you who you are.", credit: "Movie: Kung Fu Panda 2", monkeytypeId: 7696 },
    { text: "Life moves forward. No matter how much it hurts. It has to.", credit: "Show: Doctor Who", monkeytypeId: 7643 },
    { text: "There is a stubbornness about me that never can bear to be frightened at the will of others. My courage always rises with every attempt to intimidate me.", credit: "Book: Pride and Prejudice", monkeytypeId: 2898, url: "https://www.gutenberg.org/files/1342/1342-h/1342-h.htm" },
    { text: "I must learn to brook being happier than I deserve.", credit: "Captain Wentworth · Book: Persuasion", monkeytypeId: 3533, url: "https://www.gutenberg.org/files/105/old/105-h/105-h.htm" },
    { text: "And the point is, to live everything. Live the questions now.", credit: "Book: Letters to a Young Poet", monkeytypeId: 3324 },
    { text: "He's learning some things, all by himself, and hopefully learning to ask for help when he needs it.", credit: "Show: The Good Place", monkeytypeId: 6277 },
    { text: "The storm passed through us and around us. It's gone, but we remain.", credit: "Book: Dune", monkeytypeId: 6509 },
    { text: "The past can hurt. But the way I see it, you can either run from it... or learn from it.", credit: "Movie: The Lion King", monkeytypeId: 3917 },
    { text: "No matter how bad things are, you can always make things worse. At the same time, it is often within your power to make them better.", credit: "Book: The Last Lecture", monkeytypeId: 1052 },
    { text: "But that parting needs not last forever. Whether a parting be forever or merely for a short while... that is up to you.", credit: "Game: The Legend of Zelda: Majora's Mask", monkeytypeId: 845 },
    { text: "There must be quite a few things a hot bath won't cure, but I don't know many of them.", credit: "Book: The Bell Jar", monkeytypeId: 839 },
    { text: "When you meet someone better than yourself, turn your thoughts to becoming his equal.", credit: "Book: The Analects", monkeytypeId: 840 },
    { text: "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair...", credit: "Book: The Fellowship of the Ring", monkeytypeId: 1357 },
  ],
  humor: [
    // Stronger selections from the user's examples.
    { text: "Maybe if we tell people the brain is an app, they will start using it.", credit: "Unknown · Supplied example" },
    { text: "I find television very educational. Every time someone turns it on, I go into the other room and read a book.", credit: "Groucho Marx · Humorist", url: "https://quoteinvestigator.com/2014/01/18/groucho-tv/" },
    { text: "Consider the postage stamp: its usefulness consists in the ability to stick to one thing ’til it gets there.", credit: "Josh Billings · Humorist", url: "https://www.quotationspage.com/quote/26878.html" },
    { text: "Even if you are on the right track, you will get run over if you just sit there.", credit: "Tom Sims · Column: Tom Sims Says", url: "https://quoteinvestigator.com/2025/01/26/right-track/" },
    { text: "People often say that motivation doesn’t last. Well, neither does bathing — that’s why we recommend it daily.", credit: "Zig Ziglar · Speaker", url: "https://www.ziglar.com/quotes/" },
    // Original observations for this tracker; do not attribute them to a person or work.
    { text: "An all-nighter is borrowing time from tomorrow at a terrible interest rate.", credit: "Tracker original · Study" },
    { text: "Group projects are like distributed systems: one node does the work, and everyone reports success.", credit: "Tracker original · BTech" },
    { text: "The exam did not come early. It arrived on the date printed on the timetable.", credit: "Tracker original · BTech" },
    { text: "I understood recursion perfectly—until I had to explain when it stops.", credit: "Tracker original · DSA" },
    { text: "Your notes are a backup only if you can understand them a week later.", credit: "Tracker original · Study" },
    { text: "The first step in solving a problem is admitting that staring at it is not an algorithm.", credit: "Tracker original · DSA" },
    { text: "Being ‘almost done’ is a brave claim for code that has not compiled.", credit: "Tracker original · Coding" },
    { text: "A tutorial feels easy because the person in the video already knows what happens next.", credit: "Tracker original · Study" },
    { text: "You can rename the file final_v3, but that does not make the assignment finished.", credit: "Tracker original · BTech" },
    { text: "The syllabus has not grown. My awareness of it has.", credit: "Tracker original · BTech" },
    { text: "The quickest way to discover a missing edge case is to say, ‘This should pass everything.’", credit: "Tracker original · DSA" },
    { text: "The most efficient part of our group project was assigning ourselves job titles.", credit: "Tracker original · BTech" },
    { text: "An error message is the computer's way of saying it read the assignment more carefully than you did.", credit: "Tracker original · Coding" },
    { text: "I don't fear hard problems. I fear the easy ones that take forty minutes.", credit: "Tracker original · DSA" },
    { text: "Nothing builds character like finding the typo after rewriting the entire solution.", credit: "Tracker original · Coding" },
    { text: "My solution passed the sample case and immediately requested retirement.", credit: "Tracker original · DSA" },
    { text: "A ‘small change’ is a unit of time measured by people who won't be making it.", credit: "Tracker original · Coding" },
    { text: "Rubber duck debugging works because the duck never interrupts to suggest a new framework.", credit: "Tracker original · Coding" },
    { text: "One bug had a stack trace. The other had my name on the commit.", credit: "Tracker original · Coding" },
    { text: "The compiler says ‘expected semicolon’ with a confidence I wish I had in exams.", credit: "Tracker original · BTech" },
    { text: "I read the editorial after solving it and feel clever. I read it before solving it and call it research.", credit: "Tracker original · DSA" },
  ],
};
