// Banner content lives here so it works both from file:// and on GitHub Pages.
// inspiration: attributed excerpts with provenance. humor: selected reader examples
// plus original tracker lines. Keep uncertain authors as Unknown, never guess a name.
const TRACKER_CONTENT = {
  inspiration: [
    { text: "Marilla, isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?", credit: "Anne Shirley · Book: Anne of Green Gables", url: "https://www.gutenberg.org/files/45/45-h/45-h" },
    { text: "I’m not afraid of storms, for I’m learning how to sail my ship.", credit: "Amy March · Book: Little Women", url: "https://www.gutenberg.org/cache/epub/514/pg514-images.html" },
    { text: "Where you tend a rose, my lad, a thistle cannot grow.", credit: "Frances Hodgson Burnett · Book: The Secret Garden", url: "https://www.gutenberg.org/files/113/old/113-h/113-h.htm" },
    { text: "No, we are all in the gutter, but some of us are looking at the stars.", credit: "Lord Darlington · Play: Lady Windermere’s Fan", url: "https://www.gutenberg.org/files/790/790-h/790-h" },
    { text: "Our doubts are traitors and makes us lose the good we oft might win by fearing to attempt.", credit: "Lucio · Play: Measure for Measure", url: "https://www.folger.edu/explore/shakespeares-works/measure-for-measure/read/1/4/" },
    { text: "Stay hungry. Stay foolish.", credit: "Steve Jobs · Speech: Stanford commencement, 2005", url: "https://news.stanford.edu/stories/2005/06/steve-jobs-2005-graduates-stay-hungry-stay-foolish" },
    { text: "No! Try not. Do. Or do not. There is no try.", credit: "Yoda · Movie: The Empire Strikes Back", url: "https://www.starwars.com/news/empire-at-40-teaching-with-star-wars-the-wisdom-of-do-or-do-not" },
    { text: "One child, one teacher, one pen and one book can change the world.", credit: "Malala Yousafzai · Speech: United Nations, 2013", url: "https://malala.org/news-and-voices/malala-un-speech" },
    { text: "It’s your place in the world; it’s your life. Go on and do all you can with it…", credit: "Mae Jemison · Person", url: "https://ntrs.nasa.gov/api/citations/20190032275/downloads/20190032275.pdf?attachment=true" },
    { text: "You have plenty of courage, I am sure. All you need is confidence in yourself.", credit: "Oz · Book: The Wonderful Wizard of Oz", url: "https://www.gutenberg.org/files/43936/43936-h/43936-h" },
    { text: "There is no charm equal to tenderness of heart.", credit: "Emma Woodhouse · Book: Emma", url: "https://dev.gutenberg.org/files/158/158-h/158-h.htm" },
    { text: "Wait and hope.", credit: "Edmond Dantès · Book: The Count of Monte Cristo", url: "https://dev.gutenberg.org/files/1184/1184-h/1184-h.htm" },
    { text: "We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard…", credit: "John F. Kennedy · Speech: Rice University, 1962", url: "https://www.rice.edu/kennedy" },
    { text: "The only thing we have to fear is fear itself.", credit: "Franklin D. Roosevelt · Speech: First inaugural address", url: "https://www.archives.gov/education/lessons/fdr-inaugural" },
    { text: "Why, sometimes I’ve believed as many as six impossible things before breakfast.", credit: "The White Queen · Book: Through the Looking-Glass", url: "https://dev.gutenberg.org/cache/epub/12/pg12-images.html" },
    { text: "Where the mind is without fear and the head is held high;", credit: "Rabindranath Tagore · Book: Gitanjali", url: "https://www.gutenberg.org/cache/epub/7164/pg7164-images.html" },
    { text: "Optimism is the faith that leads to achievement; nothing can be done without hope.", credit: "Helen Keller · Person", url: "https://afb.org/about-afb/history/helen-keller/helen-keller-quotes/helen-keller-quotes-optimism" },
    { text: "If you have built castles in the air, your work need not be lost; that is where they should be.", credit: "Henry David Thoreau · Book: Walden", url: "https://www.gutenberg.org/files/205/205-h/205-h.htm" },
    { text: "Trust thyself: every heart vibrates to that iron string.", credit: "Ralph Waldo Emerson · Essay: Self-Reliance", url: "https://www.gutenberg.org/cache/epub/2944/pg2944-images.html" },
    { text: "What I cannot create, I do not understand.", credit: "Richard Feynman · Person", url: "https://magazine.caltech.edu/post/biology-through-the-eyes-of-a-physicist" },
    { text: "It is hard to fail, but it is worse never to have tried to succeed.", credit: "Theodore Roosevelt · Person", url: "https://www.theodorerooseveltcenter.org/quote/it-is-hard-to-fail-but-it-is-worse-never-to-have-tried-to-succeed-in-this-life-we-get-nothing-save-by-effort/" },
    // Monkeytype trial picks from:
    // https://github.com/monkeytypegame/monkeytype/blob/master/frontend/static/quotes/english.json
    // IDs preserve provenance for review; these are not claims of speaker-level verification.
    { text: "You must take life the way it comes at you and make the best of it.", credit: "Book: Life of Pi", monkeytypeId: 6 },
    { text: "There are darknesses in life, and there are lights; you are one of the lights.", credit: "Book: Dracula", monkeytypeId: 14, url: "https://www.gutenberg.org/files/345/345-h/345-h" },
    { text: "If you only do what you can do, you will never be more than who you are now.", credit: "Movie: Kung Fu Panda", monkeytypeId: 16 },
    { text: "Courage is resistance to fear, mastery of fear—not absence of fear.", credit: "Mark Twain · Book: Pudd’nhead Wilson", monkeytypeId: 36, url: "https://quoteinvestigator.com/2019/11/26/courage-fear/" },
    { text: "If you want a happy ending, that depends, of course, on where you stop your story.", credit: "Show: White Collar", monkeytypeId: 844 },
    { text: "When do I know I'm Spider-Man? You won't. That's all it is Miles. A leap of faith.", credit: "Movie: Spider-Man: Into the Spider-Verse", monkeytypeId: 5737 },
    { text: "There is nothing wrong with letting the people who love you help you.", credit: "Show: Avatar: The Last Airbender", monkeytypeId: 5396 },
    { text: "Your story may not have such a happy beginning, but that doesn't make you who you are.", credit: "Movie: Kung Fu Panda 2", monkeytypeId: 7696 },
    { text: "Life moves forward. No matter how much it hurts. It has to.", credit: "Show: Doctor Who", monkeytypeId: 7643 },
    { text: "There is a stubbornness about me that never can bear to be frightened at the will of others. My courage always rises with every attempt to intimidate me.", credit: "Book: Pride and Prejudice", monkeytypeId: 2898, url: "https://www.gutenberg.org/files/1342/1342-h/1342-h.htm" },
    { text: "I must learn to brook being happier than I deserve.", credit: "Captain Wentworth · Book: Persuasion", monkeytypeId: 3533, url: "https://www.gutenberg.org/files/105/old/105-h/105-h.htm" },
    { text: "And the point is, to live everything. Live the questions now.", credit: "Book: Letters to a Young Poet", monkeytypeId: 3324 },
    { text: "He's learning some things, all by himself, and hopefully learning to ask for help when he needs it.", credit: "Show: The Good Place", monkeytypeId: 6277 },
    { text: "The storm passed through us and around us. It's gone, but we remain.", credit: "Book: Dune", monkeytypeId: 6509 },
    { text: "The past can hurt. But the way I see it, you can either run from it... or learn from it.", credit: "Movie: The Lion King", monkeytypeId: 3917 },
    { text: "No matter how bad things are, you can always make things worse. At the same time, it is often within your power to make them better.", credit: "Book: The Last Lecture", monkeytypeId: 1052 },
    { text: "But that parting needs not last forever. Whether a parting be forever or merely for a short while... that is up to you.", credit: "Game: The Legend of Zelda: Majora's Mask", monkeytypeId: 845 },
    { text: "There must be quite a few things a hot bath won't cure, but I don't know many of them.", credit: "Book: The Bell Jar", monkeytypeId: 839 },
    { text: "When you meet someone better than yourself, turn your thoughts to becoming his equal.", credit: "Book: The Analects", monkeytypeId: 840 },
    { text: "The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair...", credit: "Book: The Fellowship of the Ring", monkeytypeId: 1357 },
  ],
  humor: [
    // Selected from the user's examples. These are not all independently attributable.
    { text: "Maybe if we tell people the brain is an app, they will start using it.", credit: "Unknown · Supplied example" },
    { text: "I find television very educational. Every time someone turns it on, I go into the other room and read a book.", credit: "Groucho Marx · Humorist", url: "https://quoteinvestigator.com/2014/01/18/groucho-tv/" },
    { text: "Consider the postage stamp: its usefulness consists in the ability to stick to one thing ’til it gets there.", credit: "Josh Billings · Humorist", url: "https://www.quotationspage.com/quote/26878.html" },
    { text: "Even if you are on the right track, you will get run over if you just sit there.", credit: "Tom Sims · Column: Tom Sims Says", url: "https://quoteinvestigator.com/2025/01/26/right-track/" },
    { text: "People often say that motivation doesn’t last. Well, neither does bathing — that’s why we recommend it daily.", credit: "Zig Ziglar · Speaker", url: "https://www.ziglar.com/quotes/" },
    { text: "I am not lazy. I am on energy-saving mode.", credit: "Unknown · Supplied example" },
    { text: "The best time to start studying was last month. The second best time is after one more episode.", credit: "Unknown · Supplied example" },
    { text: "There are three kinds of people: those who make things happen, those who watch, and those who ask, ‘What happened?’", credit: "Unknown · Supplied example" },
    // New lines written for this tracker; no external person is being quoted.
    { text: "An all-nighter is borrowing time from tomorrow at a terrible interest rate.", credit: "Tracker original · Study" },
    { text: "Group projects are like distributed systems: one node does the work, and everyone reports success.", credit: "Tracker original · BTech" },
    { text: "Your future self has filed a complaint about your current study schedule.", credit: "Tracker original · Study" },
    { text: "The exam did not come early. It arrived on the date printed on the timetable.", credit: "Tracker original · BTech" },
    { text: "I understood recursion perfectly—until I had to explain when it stops.", credit: "Tracker original · DSA" },
    { text: "A deadline can make you write code faster. It cannot make the code understand what you meant.", credit: "Tracker original · Coding" },
    { text: "Your notes are a backup only if you can understand them a week later.", credit: "Tracker original · Study" },
    { text: "The first step in solving a problem is admitting that staring at it is not an algorithm.", credit: "Tracker original · DSA" },
    { text: "My career plan has two steps: practise DSA, and stop making a new career plan every Tuesday.", credit: "Tracker original · Student life" },
    { text: "Being ‘almost done’ is a brave claim for code that has not compiled.", credit: "Tracker original · Coding" },
    { text: "The test cases are not judging you. They just have a very specific way of expressing disappointment.", credit: "Tracker original · Coding" },
    { text: "A tutorial feels easy because the person in the video already knows what happens next.", credit: "Tracker original · Study" },
    { text: "You can rename the file final_v3, but that does not make the assignment finished.", credit: "Tracker original · BTech" },
    { text: "The bug was not hiding. I was looking everywhere except the line I had just changed.", credit: "Tracker original · Coding" },
    { text: "My code has two states: working, and improved.", credit: "Tracker original · Coding" },
    { text: "Every difficult problem is easy once you have seen the solution. That is why we practise before seeing it.", credit: "Tracker original · DSA" },
    { text: "The syllabus has not grown. My awareness of it has.", credit: "Tracker original · BTech" },
    { text: "A streak is not a personality trait. It is a series of days you decided to show up.", credit: "Tracker original · Study" },
    { text: "If you keep waiting to feel ready, the deadline will make the decision for you.", credit: "Tracker original · Study" },
    { text: "The quickest way to discover a missing edge case is to say, ‘This should pass everything.’", credit: "Tracker original · DSA" },
  ],
};
