// Generated by reference/scripts/build_solutions.py - do not hand-edit.
// Source of truth is reference/solutions/<problem-id>.json, one file per problem.
// To add a solution: write that file (trick/time/space/code), then rerun the
// build script. Every entry here was compiled and cross-checked before being
// added - see the commit that introduced it for how.
const SOLUTIONS = {
  "s1-armstrong-numbers": {
    trick: "Count decimal digits, then sum each digit raised to that count; compare with the original number.",
    time: "O(d\u00b2) with repeated multiplication",
    space: "O(1)",
    code: "bool isArmstrong(int n) {\n    if (n < 0) return false;\n    int digits = 0, t = n;\n    do { ++digits; t /= 10; } while (t);\n    long long sum = 0;\n    t = n;\n    do {\n        int digit = t % 10;\n        long long power = 1;\n        for (int i = 0; i < digits; ++i) power *= digit;\n        sum += power;\n        t /= 10;\n    } while (t);\n    return sum == n;\n}",
  },
  "s1-check-for-prime": {
    trick: "A composite number has a factor no larger than its square root.",
    time: "O(\u221an)",
    space: "O(1)",
    code: "bool isPrime(int n) {\n    if (n < 2) return false;\n    for (int d = 2; d <= n / d; ++d)\n        if (n % d == 0) return false;\n    return true;\n}",
  },
  "s1-check-palindrome": {
    trick: "Reverse the number the same way as above, then compare it to the original.",
    time: "O(log\u2081\u2080 n)",
    space: "O(1)",
    code: "bool isPalindrome(int n) {\n    int original = n, rev = 0;\n    while (n != 0) {\n        rev = rev * 10 + (n % 10);\n        n /= 10;\n    }\n    return original == rev;\n}",
  },
  "s1-count-digits": {
    trick: "Repeatedly divide by 10 until it's 0, counting each division. Zero itself has exactly one digit.",
    time: "O(log\u2081\u2080 n)",
    space: "O(1)",
    code: "int countDigits(int n) {\n    if (n == 0) return 1;\n    int count = 0;\n    while (n != 0) {\n        count++;\n        n /= 10;\n    }\n    return count;\n}",
  },
  "s1-counting-frequencies-of-array-elements": {
    trick: "Increment a hash-map count for each value; the map is the frequency table.",
    time: "O(n) expected",
    space: "O(u), u = distinct values",
    code: "unordered_map<int, int> frequencies(const vector<int>& arr) {\n    unordered_map<int, int> count;\n    for (int value : arr) ++count[value];\n    return count;\n}",
  },
  "s1-gcd-or-hcf": {
    trick: "Euclid's algorithm: gcd(a, b) = gcd(b, a % b). Keep replacing the pair until b hits 0 \u2014 a is the answer.",
    time: "O(log(min(a, b)))",
    space: "O(1)",
    code: "int gcd(int a, int b) {\n    while (b != 0) {\n        int temp = b;\n        b = a % b;\n        a = temp;\n    }\n    return a;\n}",
  },
  "s1-print-all-divisors": {
    trick: "Every divisor below sqrt(n) pairs with n/divisor; collect both and sort for ascending output.",
    time: "O(\u221an + d log d)",
    space: "O(d), d = number of divisors",
    code: "vector<int> divisors(int n) {\n    vector<int> ans;\n    if (n <= 0) return ans;\n    for (int d = 1; d <= n / d; ++d) {\n        if (n % d == 0) {\n            ans.push_back(d);\n            if (d != n / d) ans.push_back(n / d);\n        }\n    }\n    sort(ans.begin(), ans.end());\n    return ans;\n}",
  },
  "s1-reverse-a-number": {
    trick: "Pull the last digit off with n % 10, push it onto the answer with rev*10 + digit, then drop the last digit from n.",
    time: "O(log\u2081\u2080 n)",
    space: "O(1)",
    code: "int reverseNumber(int n) {\n    int rev = 0;\n    while (n != 0) {\n        rev = rev * 10 + (n % 10);\n        n /= 10;\n    }\n    return rev;\n}",
  },
  "s2-bubble-sort": {
    trick: "Repeatedly swap adjacent out-of-order pairs, bubbling the largest unsorted element to the end each pass. Stop early if a pass makes no swaps \u2014 the array is already sorted.",
    time: "O(n\u00b2), O(n) if already sorted",
    space: "O(1)",
    code: "void bubbleSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = n - 1; i > 0; i--) {\n        bool swapped = false;\n        for (int j = 0; j < i; j++) {\n            if (arr[j] > arr[j + 1]) {\n                swap(arr[j], arr[j + 1]);\n                swapped = true;\n            }\n        }\n        if (!swapped) break;\n    }\n}",
  },
  "s2-insertion-sort": {
    trick: "Build the sorted prefix one element at a time: take the next element and shift larger elements right until it finds its spot \u2014 like sorting playing cards in your hand.",
    time: "O(n\u00b2), O(n) if already sorted",
    space: "O(1)",
    code: "void insertionSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = 1; i < n; i++) {\n        int key = arr[i], j = i - 1;\n        while (j >= 0 && arr[j] > key) {\n            arr[j + 1] = arr[j];\n            j--;\n        }\n        arr[j + 1] = key;\n    }\n}",
  },
  "s2-merge-sort": {
    trick: "Split the array in half recursively until pieces are size 1, then merge sorted halves back together by repeatedly taking the smaller of the two fronts.",
    time: "O(n log n)",
    space: "O(n)",
    code: "void merge(vector<int>& arr, int low, int mid, int high) {\n    vector<int> temp;\n    int left = low, right = mid + 1;\n    while (left <= mid && right <= high) {\n        if (arr[left] <= arr[right]) temp.push_back(arr[left++]);\n        else temp.push_back(arr[right++]);\n    }\n    while (left <= mid) temp.push_back(arr[left++]);\n    while (right <= high) temp.push_back(arr[right++]);\n    for (int i = low; i <= high; i++) arr[i] = temp[i - low];\n}\n\nvoid mergeSort(vector<int>& arr, int low, int high) {\n    if (low >= high) return;\n    int mid = (low + high) / 2;\n    mergeSort(arr, low, mid);\n    mergeSort(arr, mid + 1, high);\n    merge(arr, low, mid, high);\n}",
  },
  "s2-quick-sort": {
    trick: "Pick a pivot (the first element here), partition the array so smaller elements end up left of it and larger ones right, then recursively sort each side.",
    time: "O(n log n) average, O(n\u00b2) worst case",
    space: "O(log n) recursion stack",
    code: "int partition(vector<int>& arr, int low, int high) {\n    int pivot = arr[low], i = low, j = high;\n    while (i < j) {\n        while (arr[i] <= pivot && i <= high - 1) i++;\n        while (arr[j] > pivot && j >= low + 1) j--;\n        if (i < j) swap(arr[i], arr[j]);\n    }\n    swap(arr[low], arr[j]);\n    return j;\n}\n\nvoid quickSort(vector<int>& arr, int low, int high) {\n    if (low < high) {\n        int p = partition(arr, low, high);\n        quickSort(arr, low, p - 1);\n        quickSort(arr, p + 1, high);\n    }\n}",
  },
  "s2-recursive-bubble-sort": {
    trick: "Same idea as bubble sort \u2014 one pass bubbles the largest remaining element to the end \u2014 but each pass is a recursive call on a shrinking prefix instead of an outer loop.",
    time: "O(n\u00b2)",
    space: "O(n) recursion stack",
    code: "void recursiveBubbleSort(vector<int>& arr, int n) {\n    if (n <= 1) return;\n    for (int j = 0; j < n - 1; j++)\n        if (arr[j] > arr[j + 1]) swap(arr[j], arr[j + 1]);\n    recursiveBubbleSort(arr, n - 1);\n}",
  },
  "s2-recursive-insertion-sort": {
    trick: "Recursively sort the first n-1 elements first, then insert the nth element into its correct position by shifting larger elements right.",
    time: "O(n\u00b2)",
    space: "O(n) recursion stack",
    code: "void recursiveInsertionSort(vector<int>& arr, int n) {\n    if (n <= 1) return;\n    recursiveInsertionSort(arr, n - 1);\n    int last = arr[n - 1], j = n - 2;\n    while (j >= 0 && arr[j] > last) {\n        arr[j + 1] = arr[j];\n        j--;\n    }\n    arr[j + 1] = last;\n}",
  },
  "s2-selection-sort": {
    trick: "Find the minimum in the unsorted part of the array and swap it to the front. Repeat for each position.",
    time: "O(n\u00b2)",
    space: "O(1)",
    code: "void selectionSort(vector<int>& arr) {\n    int n = arr.size();\n    for (int i = 0; i < n - 1; i++) {\n        int minIdx = i;\n        for (int j = i + 1; j < n; j++)\n            if (arr[j] < arr[minIdx]) minIdx = j;\n        swap(arr[i], arr[minIdx]);\n    }\n}",
  },
  "s3-check-if-the-array-is-sorted": {
    trick: "Sorted means every element is \u2265 the one before it. One pass, bail out at the first drop.",
    time: "O(n)",
    space: "O(1)",
    code: "bool isSorted(vector<int>& arr) {\n    for (size_t i = 1; i < arr.size(); i++)\n        if (arr[i] < arr[i - 1]) return false;\n    return true;\n}",
  },
  "s3-find-missing-number-in-an-array": {
    trick: "Numbers 1..n should sum to n(n+1)/2. Whatever's short in the actual sum is the missing number.",
    time: "O(n)",
    space: "O(1)",
    code: "int findMissingNumber(vector<int>& arr, int n) {\n    long long expectedSum = (long long)n * (n + 1) / 2;\n    long long actualSum = 0;\n    for (int x : arr) actualSum += x;\n    return (int)(expectedSum - actualSum);\n}",
  },
  "s3-find-the-number-that-appears-once-and-other-numb": {
    trick: "XOR cancels each paired value, leaving the unpaired value.",
    time: "O(n)",
    space: "O(1)",
    code: "int singleNumber(const vector<int>& arr) {\n    int answer = 0;\n    for (int value : arr) answer ^= value;\n    return answer;\n}",
  },
  "s3-kadane-s-algorithm-maximum-subarray-sum": {
    trick: "Extend the running sum while it helps; the moment it goes negative it can only drag future sums down, so reset to 0. Track the best sum seen at any point \u2014 even a single (negative) element counts.",
    time: "O(n)",
    space: "O(1)",
    code: "long long maxSubArraySum(vector<int>& arr) {\n    long long best = LLONG_MIN, current = 0;\n    for (int x : arr) {\n        current += x;\n        best = max(best, current);\n        if (current < 0) current = 0;\n    }\n    return best;\n}",
  },
  "s3-largest-element-in-an-array": {
    trick: "Keep the largest value seen while scanning once.",
    time: "O(n)",
    space: "O(1)",
    code: "int largest(const vector<int>& arr) {\n    if (arr.empty()) throw invalid_argument(\"array must be nonempty\");\n    int best = arr[0];\n    for (int value : arr) best = max(best, value);\n    return best;\n}",
  },
  "s3-left-rotate-an-array-by-d-places": {
    trick: "Reduce d modulo n, then reverse the first d, remaining n-d, and whole array.",
    time: "O(n)",
    space: "O(1)",
    code: "void rotateLeft(vector<int>& arr, int d) {\n    int n = static_cast<int>(arr.size());\n    if (n == 0) return;\n    d = (d % n + n) % n;\n    reverse(arr.begin(), arr.begin() + d);\n    reverse(arr.begin() + d, arr.end());\n    reverse(arr.begin(), arr.end());\n}",
  },
  "s3-left-rotate-an-array-by-one-place": {
    trick: "Save the first element, shift the rest left, then place the saved element at the end.",
    time: "O(n)",
    space: "O(1)",
    code: "void rotateLeftOne(vector<int>& arr) {\n    if (arr.empty()) return;\n    int first = arr[0];\n    for (size_t i = 1; i < arr.size(); ++i) arr[i - 1] = arr[i];\n    arr.back() = first;\n}",
  },
  "s3-maximum-consecutive-ones": {
    trick: "Grow the current run for a one; reset it at a zero, tracking the maximum.",
    time: "O(n)",
    space: "O(1)",
    code: "int maxConsecutiveOnes(const vector<int>& bits) {\n    int run = 0, best = 0;\n    for (int bit : bits) {\n        run = bit == 1 ? run + 1 : 0;\n        best = max(best, run);\n    }\n    return best;\n}",
  },
  "s3-move-zeros-to-end": {
    trick: "Copy nonzero values forward in their original order, then fill the suffix with zeros.",
    time: "O(n)",
    space: "O(1)",
    code: "void moveZeros(vector<int>& arr) {\n    size_t write = 0;\n    for (int value : arr) if (value != 0) arr[write++] = value;\n    while (write < arr.size()) arr[write++] = 0;\n}",
  },
  "s3-remove-duplicates-from-sorted-array": {
    trick: "Write each value that differs from the last kept value into the next free prefix position.",
    time: "O(n)",
    space: "O(1)",
    code: "int removeDuplicates(vector<int>& arr) {\n    int write = 0;\n    for (int value : arr)\n        if (write == 0 || value != arr[write - 1]) arr[write++] = value;\n    return write; // unique values occupy arr[0..write-1]\n}",
  },
  "s3-second-largest-element-in-an-array-without-sorti": {
    trick: "Track the largest and second-largest in one pass. When a new largest appears, the old largest demotes to second. Skip values equal to the current largest so duplicates of the max don't count as a second.",
    time: "O(n)",
    space: "O(1)",
    code: "int secondLargest(vector<int>& arr) {\n    int largest = INT_MIN, second = INT_MIN;\n    for (int x : arr) {\n        if (x > largest) {\n            second = largest;\n            largest = x;\n        } else if (x > second && x < largest) {\n            second = x;\n        }\n    }\n    return second == INT_MIN ? -1 : second;\n}",
  },
};
